#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inwentarz
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Albumy")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Inwentarz.Properties.Settings.Default.AlbumyConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Albumy> Albumy
		{
			get
			{
				return this.GetTable<Albumy>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Albumy")]
	public partial class Albumy
	{
		
		private int _Identyfikator;
		
		private string _Wykonawca;
		
		private string _Tytuł;
		
		private System.Nullable<int> _Rok_wydania;
		
		private System.Nullable<decimal> _Cena;
		
		private System.Nullable<int> _Ilość;
		
		private string _Stan;
		
		public Albumy()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identyfikator", DbType="Int NOT NULL")]
		public int Identyfikator
		{
			get
			{
				return this._Identyfikator;
			}
			set
			{
				if ((this._Identyfikator != value))
				{
					this._Identyfikator = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wykonawca", DbType="NVarChar(255)")]
		public string Wykonawca
		{
			get
			{
				return this._Wykonawca;
			}
			set
			{
				if ((this._Wykonawca != value))
				{
					this._Wykonawca = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tytuł", DbType="NVarChar(MAX)")]
		public string Tytuł
		{
			get
			{
				return this._Tytuł;
			}
			set
			{
				if ((this._Tytuł != value))
				{
					this._Tytuł = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Rok wydania]", Storage="_Rok_wydania", DbType="Int")]
		public System.Nullable<int> Rok_wydania
		{
			get
			{
				return this._Rok_wydania;
			}
			set
			{
				if ((this._Rok_wydania != value))
				{
					this._Rok_wydania = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cena", DbType="Money")]
		public System.Nullable<decimal> Cena
		{
			get
			{
				return this._Cena;
			}
			set
			{
				if ((this._Cena != value))
				{
					this._Cena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilość", DbType="Int")]
		public System.Nullable<int> Ilość
		{
			get
			{
				return this._Ilość;
			}
			set
			{
				if ((this._Ilość != value))
				{
					this._Ilość = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stan", DbType="NVarChar(255)")]
		public string Stan
		{
			get
			{
				return this._Stan;
			}
			set
			{
				if ((this._Stan != value))
				{
					this._Stan = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
